name = "pyonk"
description = "A modern Hugo theme with Preact components"
features = ["blog", "preact", "dark-mode", "responsive"]
homepage = "https://github.com/pyonk/blog"
license = "MIT"
min_version = "0.110.0"
tags = [
  "blog",
  "clean",
  "customizable",
  "dark",
  "light",
  "minimal",
  "modern",
  "preact",
  "responsive",
  "simple"
]

[author]
name = "pyonk"