baseurl: "https://pyonk.github.io/blog/"
config: "config.yaml"
languageCode: "ja"
title: "pyonk Blog"
disqusShortname: "pyonk"
enableEmoji: true
metaDataFormat: "yaml"
noTimes: true

Params:
  subtitle: "いろいろ"
  facebook: "https://facebook.com/yukiyoshiokap"
  twitter: "https://twitter.com/yukieroero"
  #github: "https://github.com/foobar"
  showsRSS: false
  profile: "/images/prof.jpg"
  logo: "/images/prof.jpg"
  #copyright: "Written by Asuka Suzuki"
  #analytics: "UA-XXXXXXXX-X"
  #shareThis = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
  blackfriday:
    hrefTargetBlank: true
