baseurl: "https://pyonk.github.io/blog/"
config: "config.yaml"
languageCode: "ja"
title: "わいがかいた"
disqusShortname: "pyonk"
enableEmoji: true
metaDataFormat: "yaml"
noTimes: true
GoogleAnalytics: "UA-85825684-1"
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsOptions:
  linenos: "table"

Params:
  subtitle: "いろいろ"
  facebook: "https://facebook.com/yukiyoshiokap"
  twitter: "https://twitter.com/yukieroero"
  github: "https://github.com/pyonk"
  showsRSS: false
  profile: "/blog/images/prof.jpg"
  logo: "/blog/images/prof.jpg"
  copyright: "pyonk All rights reserved."
  # analytics: "UA-85825684-1"
  #shareThis = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
  blackfriday:
   hrefTargetBlank: true

Copyright: "pyonk"
